###############################################################
# Program:
#     Assignment 04, Product inventory
#     Brother Alvey, CS165
# Author:
#     Coby Jenkins
# Summary:
#     Demonstration of the usage of classes and  how to create the necessary
#       parts.
###############################################################


# We will learn fancier compilation steps later, but this is
# good enough for now...
a.out : product.h product.cpp assign04.cpp
	g++ product.cpp assign04.cpp

